version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    db:
        image: postgres
        restart: always
        environment:
          - PGPORT=7001
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=res_review2020@
        ports:
          - "7001:5432"